//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.20506.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.20506.1.
// 
#pragma warning disable 1591

namespace _g.SMLJAVAWS_PO1 {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.20506.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SMLFrameWorkSoapBinding", Namespace="http://smlpackage")]
    public partial class SMLFrameWorkService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback _invoiceGetqueryCompressOperationCompleted;
        
        private System.Threading.SendOrPostCallback _invoiceGetqueryOperationCompleted;
        
        private System.Threading.SendOrPostCallback _invoiceGetquerySearchCompressOperationCompleted;
        
        private System.Threading.SendOrPostCallback _invoiceGetquerySearchOperationCompleted;
        
        private System.Threading.SendOrPostCallback _dePositGetqueryOperationCompleted;
        
        private System.Threading.SendOrPostCallback _dePositGetquerySearchCompressOperationCompleted;
        
        private System.Threading.SendOrPostCallback _dePositGetquerySearchOperationCompleted;
        
        private System.Threading.SendOrPostCallback _dePositGetqueryCompressOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SMLFrameWorkService() {
            this.Url = global::_g.Properties.Settings.Default.SMLERPGlobal_SMLJAVAWS_PO1_SMLFrameWorkService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event _invoiceGetqueryCompressCompletedEventHandler _invoiceGetqueryCompressCompleted;
        
        /// <remarks/>
        public event _invoiceGetqueryCompletedEventHandler _invoiceGetqueryCompleted;
        
        /// <remarks/>
        public event _invoiceGetquerySearchCompressCompletedEventHandler _invoiceGetquerySearchCompressCompleted;
        
        /// <remarks/>
        public event _invoiceGetquerySearchCompletedEventHandler _invoiceGetquerySearchCompleted;
        
        /// <remarks/>
        public event _dePositGetqueryCompletedEventHandler _dePositGetqueryCompleted;
        
        /// <remarks/>
        public event _dePositGetquerySearchCompressCompletedEventHandler _dePositGetquerySearchCompressCompleted;
        
        /// <remarks/>
        public event _dePositGetquerySearchCompletedEventHandler _dePositGetquerySearchCompleted;
        
        /// <remarks/>
        public event _dePositGetqueryCompressCompletedEventHandler _dePositGetqueryCompressCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://smlpackage", ResponseNamespace="http://smlpackage", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("_invoiceGetqueryCompressReturn", DataType="base64Binary")]
        public byte[] _invoiceGetqueryCompress(string GUID, string configFileName, string databaseName, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] query) {
            object[] results = this.Invoke("_invoiceGetqueryCompress", new object[] {
                        GUID,
                        configFileName,
                        databaseName,
                        query});
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public void _invoiceGetqueryCompressAsync(string GUID, string configFileName, string databaseName, byte[] query) {
            this._invoiceGetqueryCompressAsync(GUID, configFileName, databaseName, query, null);
        }
        
        /// <remarks/>
        public void _invoiceGetqueryCompressAsync(string GUID, string configFileName, string databaseName, byte[] query, object userState) {
            if ((this._invoiceGetqueryCompressOperationCompleted == null)) {
                this._invoiceGetqueryCompressOperationCompleted = new System.Threading.SendOrPostCallback(this.On_invoiceGetqueryCompressOperationCompleted);
            }
            this.InvokeAsync("_invoiceGetqueryCompress", new object[] {
                        GUID,
                        configFileName,
                        databaseName,
                        query}, this._invoiceGetqueryCompressOperationCompleted, userState);
        }
        
        private void On_invoiceGetqueryCompressOperationCompleted(object arg) {
            if ((this._invoiceGetqueryCompressCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this._invoiceGetqueryCompressCompleted(this, new _invoiceGetqueryCompressCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://smlpackage", ResponseNamespace="http://smlpackage", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("_invoiceGetqueryReturn")]
        public string _invoiceGetquery(string GUID, string configFileName, string databaseName, string transection_flag) {
            object[] results = this.Invoke("_invoiceGetquery", new object[] {
                        GUID,
                        configFileName,
                        databaseName,
                        transection_flag});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void _invoiceGetqueryAsync(string GUID, string configFileName, string databaseName, string transection_flag) {
            this._invoiceGetqueryAsync(GUID, configFileName, databaseName, transection_flag, null);
        }
        
        /// <remarks/>
        public void _invoiceGetqueryAsync(string GUID, string configFileName, string databaseName, string transection_flag, object userState) {
            if ((this._invoiceGetqueryOperationCompleted == null)) {
                this._invoiceGetqueryOperationCompleted = new System.Threading.SendOrPostCallback(this.On_invoiceGetqueryOperationCompleted);
            }
            this.InvokeAsync("_invoiceGetquery", new object[] {
                        GUID,
                        configFileName,
                        databaseName,
                        transection_flag}, this._invoiceGetqueryOperationCompleted, userState);
        }
        
        private void On_invoiceGetqueryOperationCompleted(object arg) {
            if ((this._invoiceGetqueryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this._invoiceGetqueryCompleted(this, new _invoiceGetqueryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://smlpackage", ResponseNamespace="http://smlpackage", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("_invoiceGetquerySearchCompressReturn", DataType="base64Binary")]
        public byte[] _invoiceGetquerySearchCompress(string GUID, string configFileName, string databaseName, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] query) {
            object[] results = this.Invoke("_invoiceGetquerySearchCompress", new object[] {
                        GUID,
                        configFileName,
                        databaseName,
                        query});
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public void _invoiceGetquerySearchCompressAsync(string GUID, string configFileName, string databaseName, byte[] query) {
            this._invoiceGetquerySearchCompressAsync(GUID, configFileName, databaseName, query, null);
        }
        
        /// <remarks/>
        public void _invoiceGetquerySearchCompressAsync(string GUID, string configFileName, string databaseName, byte[] query, object userState) {
            if ((this._invoiceGetquerySearchCompressOperationCompleted == null)) {
                this._invoiceGetquerySearchCompressOperationCompleted = new System.Threading.SendOrPostCallback(this.On_invoiceGetquerySearchCompressOperationCompleted);
            }
            this.InvokeAsync("_invoiceGetquerySearchCompress", new object[] {
                        GUID,
                        configFileName,
                        databaseName,
                        query}, this._invoiceGetquerySearchCompressOperationCompleted, userState);
        }
        
        private void On_invoiceGetquerySearchCompressOperationCompleted(object arg) {
            if ((this._invoiceGetquerySearchCompressCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this._invoiceGetquerySearchCompressCompleted(this, new _invoiceGetquerySearchCompressCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://smlpackage", ResponseNamespace="http://smlpackage", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("_invoiceGetquerySearchReturn")]
        public string _invoiceGetquerySearch(string GUID, string configFileName, string databaseName, string queryForsearch) {
            object[] results = this.Invoke("_invoiceGetquerySearch", new object[] {
                        GUID,
                        configFileName,
                        databaseName,
                        queryForsearch});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void _invoiceGetquerySearchAsync(string GUID, string configFileName, string databaseName, string queryForsearch) {
            this._invoiceGetquerySearchAsync(GUID, configFileName, databaseName, queryForsearch, null);
        }
        
        /// <remarks/>
        public void _invoiceGetquerySearchAsync(string GUID, string configFileName, string databaseName, string queryForsearch, object userState) {
            if ((this._invoiceGetquerySearchOperationCompleted == null)) {
                this._invoiceGetquerySearchOperationCompleted = new System.Threading.SendOrPostCallback(this.On_invoiceGetquerySearchOperationCompleted);
            }
            this.InvokeAsync("_invoiceGetquerySearch", new object[] {
                        GUID,
                        configFileName,
                        databaseName,
                        queryForsearch}, this._invoiceGetquerySearchOperationCompleted, userState);
        }
        
        private void On_invoiceGetquerySearchOperationCompleted(object arg) {
            if ((this._invoiceGetquerySearchCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this._invoiceGetquerySearchCompleted(this, new _invoiceGetquerySearchCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://smlpackage", ResponseNamespace="http://smlpackage", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("_dePositGetqueryReturn")]
        public string _dePositGetquery(string GUID, string configFileName, string databaseName, string transection_flag) {
            object[] results = this.Invoke("_dePositGetquery", new object[] {
                        GUID,
                        configFileName,
                        databaseName,
                        transection_flag});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void _dePositGetqueryAsync(string GUID, string configFileName, string databaseName, string transection_flag) {
            this._dePositGetqueryAsync(GUID, configFileName, databaseName, transection_flag, null);
        }
        
        /// <remarks/>
        public void _dePositGetqueryAsync(string GUID, string configFileName, string databaseName, string transection_flag, object userState) {
            if ((this._dePositGetqueryOperationCompleted == null)) {
                this._dePositGetqueryOperationCompleted = new System.Threading.SendOrPostCallback(this.On_dePositGetqueryOperationCompleted);
            }
            this.InvokeAsync("_dePositGetquery", new object[] {
                        GUID,
                        configFileName,
                        databaseName,
                        transection_flag}, this._dePositGetqueryOperationCompleted, userState);
        }
        
        private void On_dePositGetqueryOperationCompleted(object arg) {
            if ((this._dePositGetqueryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this._dePositGetqueryCompleted(this, new _dePositGetqueryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://smlpackage", ResponseNamespace="http://smlpackage", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("_dePositGetquerySearchCompressReturn", DataType="base64Binary")]
        public byte[] _dePositGetquerySearchCompress(string GUID, string configFileName, string databaseName, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] query) {
            object[] results = this.Invoke("_dePositGetquerySearchCompress", new object[] {
                        GUID,
                        configFileName,
                        databaseName,
                        query});
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public void _dePositGetquerySearchCompressAsync(string GUID, string configFileName, string databaseName, byte[] query) {
            this._dePositGetquerySearchCompressAsync(GUID, configFileName, databaseName, query, null);
        }
        
        /// <remarks/>
        public void _dePositGetquerySearchCompressAsync(string GUID, string configFileName, string databaseName, byte[] query, object userState) {
            if ((this._dePositGetquerySearchCompressOperationCompleted == null)) {
                this._dePositGetquerySearchCompressOperationCompleted = new System.Threading.SendOrPostCallback(this.On_dePositGetquerySearchCompressOperationCompleted);
            }
            this.InvokeAsync("_dePositGetquerySearchCompress", new object[] {
                        GUID,
                        configFileName,
                        databaseName,
                        query}, this._dePositGetquerySearchCompressOperationCompleted, userState);
        }
        
        private void On_dePositGetquerySearchCompressOperationCompleted(object arg) {
            if ((this._dePositGetquerySearchCompressCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this._dePositGetquerySearchCompressCompleted(this, new _dePositGetquerySearchCompressCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://smlpackage", ResponseNamespace="http://smlpackage", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("_dePositGetquerySearchReturn")]
        public string _dePositGetquerySearch(string GUID, string configFileName, string databaseName, string queryForsearch) {
            object[] results = this.Invoke("_dePositGetquerySearch", new object[] {
                        GUID,
                        configFileName,
                        databaseName,
                        queryForsearch});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void _dePositGetquerySearchAsync(string GUID, string configFileName, string databaseName, string queryForsearch) {
            this._dePositGetquerySearchAsync(GUID, configFileName, databaseName, queryForsearch, null);
        }
        
        /// <remarks/>
        public void _dePositGetquerySearchAsync(string GUID, string configFileName, string databaseName, string queryForsearch, object userState) {
            if ((this._dePositGetquerySearchOperationCompleted == null)) {
                this._dePositGetquerySearchOperationCompleted = new System.Threading.SendOrPostCallback(this.On_dePositGetquerySearchOperationCompleted);
            }
            this.InvokeAsync("_dePositGetquerySearch", new object[] {
                        GUID,
                        configFileName,
                        databaseName,
                        queryForsearch}, this._dePositGetquerySearchOperationCompleted, userState);
        }
        
        private void On_dePositGetquerySearchOperationCompleted(object arg) {
            if ((this._dePositGetquerySearchCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this._dePositGetquerySearchCompleted(this, new _dePositGetquerySearchCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://smlpackage", ResponseNamespace="http://smlpackage", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("_dePositGetqueryCompressReturn", DataType="base64Binary")]
        public byte[] _dePositGetqueryCompress(string GUID, string configFileName, string databaseName, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] query) {
            object[] results = this.Invoke("_dePositGetqueryCompress", new object[] {
                        GUID,
                        configFileName,
                        databaseName,
                        query});
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public void _dePositGetqueryCompressAsync(string GUID, string configFileName, string databaseName, byte[] query) {
            this._dePositGetqueryCompressAsync(GUID, configFileName, databaseName, query, null);
        }
        
        /// <remarks/>
        public void _dePositGetqueryCompressAsync(string GUID, string configFileName, string databaseName, byte[] query, object userState) {
            if ((this._dePositGetqueryCompressOperationCompleted == null)) {
                this._dePositGetqueryCompressOperationCompleted = new System.Threading.SendOrPostCallback(this.On_dePositGetqueryCompressOperationCompleted);
            }
            this.InvokeAsync("_dePositGetqueryCompress", new object[] {
                        GUID,
                        configFileName,
                        databaseName,
                        query}, this._dePositGetqueryCompressOperationCompleted, userState);
        }
        
        private void On_dePositGetqueryCompressOperationCompleted(object arg) {
            if ((this._dePositGetqueryCompressCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this._dePositGetqueryCompressCompleted(this, new _dePositGetqueryCompressCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.20506.1")]
    public delegate void _invoiceGetqueryCompressCompletedEventHandler(object sender, _invoiceGetqueryCompressCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.20506.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class _invoiceGetqueryCompressCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal _invoiceGetqueryCompressCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public byte[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.20506.1")]
    public delegate void _invoiceGetqueryCompletedEventHandler(object sender, _invoiceGetqueryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.20506.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class _invoiceGetqueryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal _invoiceGetqueryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.20506.1")]
    public delegate void _invoiceGetquerySearchCompressCompletedEventHandler(object sender, _invoiceGetquerySearchCompressCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.20506.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class _invoiceGetquerySearchCompressCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal _invoiceGetquerySearchCompressCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public byte[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.20506.1")]
    public delegate void _invoiceGetquerySearchCompletedEventHandler(object sender, _invoiceGetquerySearchCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.20506.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class _invoiceGetquerySearchCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal _invoiceGetquerySearchCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.20506.1")]
    public delegate void _dePositGetqueryCompletedEventHandler(object sender, _dePositGetqueryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.20506.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class _dePositGetqueryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal _dePositGetqueryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.20506.1")]
    public delegate void _dePositGetquerySearchCompressCompletedEventHandler(object sender, _dePositGetquerySearchCompressCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.20506.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class _dePositGetquerySearchCompressCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal _dePositGetquerySearchCompressCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public byte[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.20506.1")]
    public delegate void _dePositGetquerySearchCompletedEventHandler(object sender, _dePositGetquerySearchCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.20506.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class _dePositGetquerySearchCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal _dePositGetquerySearchCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.20506.1")]
    public delegate void _dePositGetqueryCompressCompletedEventHandler(object sender, _dePositGetqueryCompressCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.20506.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class _dePositGetqueryCompressCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal _dePositGetqueryCompressCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public byte[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591